### ISSUE TITLE
Uncaught TypeError: Cannot read property 'locator' of null

### ISSUE THREAD

**Issue by wader** [wndhydrnt/go-signature-statusbar#13] opened 2017-01-14 11:16 UTC
Hi, after a atom packages update some days ago i get this red exception popup a lot:
```
TypeError: Cannot read property 'locator' of null
    at GoSignatureStatusbarView.displaySignature (/Users/mattias/.atom/packages/go-signature-statusbar/lib/go-signature-statusbar-view.js:82:18)
    at /Users/mattias/.atom/packages/go-signature-statusbar/lib/go-signature-statusbar-view.js:195:14
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:129:28)
    at TextEditor.module.exports.TextEditor.cursorMoved (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:2103:27)
    at Selection.module.exports.Selection.markerDidChange (/Applications/Atom.app/Contents/Resources/app.asar/src/selection.js:921:21)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/selection.js:41:24
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:129:28)
    at DisplayMarker.module.exports.DisplayMarker.notifyObservers (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/display-marker.js:248:27)
    at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/display-marker.js:53:26
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:129:28)
    at Marker.module.exports.Marker.emitChangeEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/marker.js:425:20)
    at Marker.module.exports.Marker.update (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/marker.js:366:12)
    at Marker.module.exports.Marker.setHeadPosition (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/marker.js:146:19)
    at DisplayMarker.module.exports.DisplayMarker.setHeadBufferPosition (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/display-marker.js:146:32)
    at DisplayMarker.module.exports.DisplayMarker.setHeadScreenPosition (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/display-marker.js:154:19)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/cursor.js:67:31
    at Cursor.module.exports.Cursor.changePosition (/Applications/Atom.app/Contents/Resources/app.asar/src/cursor.js:668:7)
    at Cursor.module.exports.Cursor.setScreenPosition (/Applications/Atom.app/Contents/Resources/app.asar/src/cursor.js:65:19)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:1874:23
    at TextEditor.module.exports.TextEditor.moveCursors (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:2097:9)
    at TextEditor.module.exports.TextEditor.setCursorScreenPosition (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:1873:19)
    at TextEditorComponent.module.exports.TextEditorComponent.onMouseDown (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor-component.js:722:25)
    at HTMLDivElement.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor-component.js:3:59)
```

When I check which version of go-plus that is installed in the packages list the version is "undefined".

Could it be some local config causing it?

**Comment by joefitzgerald** [comment] 2017-01-14 16:15
1. Ensure you are running the latest version of `Atom`
1. Ensure you are running the latest version of `go-plus`

**Comment by wader** [comment] 2017-01-15 11:28
Sorry

Atom version is 1.13.0
go-plus version is 5.10 (first the version showed up as "undefined" but after a package reinstalled it showed up)

After a start with `--clear-window-state` the exception seems to be disappeared. I can let you know if I see it again. Close issue if you want.

**Comment by wndhydrnt** [comment] 2017-01-22 16:18
@wader I've not been able to reproduce the error you are seeing so I'm closing this issue for now as you suggested. If you get the popup again, feel free to reopen it.

**Closed as completed by wndhydrnt** 2017-01-22 16:18 UTC

**Comment by wader** [comment] 2017-01-22 16:45
@wndhydrnt ok! will do

**Comment by jasonmccallister** [comment] 2017-01-30 00:57
I just got this same issue. 

Here is the stack trace:

```
/Users/jasonmccallister/.atom/packages/go-signature-statusbar/lib/go-signature-statusbar-view.js:82
Hide Stack Trace
TypeError: Cannot read property 'locator' of null
    at GoSignatureStatusbarView.displaySignature (/Users/jasonmccallister/.atom/packages/go-signature-statusbar/lib/go-signature-statusbar-view.js:82:18)
    at /Users/jasonmccallister/.atom/packages/go-signature-statusbar/lib/go-signature-statusbar-view.js:195:14
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:129:28)
    at TextEditor.module.exports.TextEditor.cursorMoved (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:2102:27)
    at Selection.module.exports.Selection.markerDidChange (/Applications/Atom.app/Contents/Resources/app.asar/src/selection.js:921:21)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/selection.js:41:24
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:129:28)
    at DisplayMarker.module.exports.DisplayMarker.notifyObservers (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/display-marker.js:248:27)
    at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/display-marker.js:53:26
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:129:28)
    at Marker.module.exports.Marker.emitChangeEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/marker.js:425:20)
    at Marker.module.exports.Marker.update (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/marker.js:366:12)
    at Marker.module.exports.Marker.setHeadPosition (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/marker.js:146:19)
    at DisplayMarker.module.exports.DisplayMarker.setHeadBufferPosition (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/display-marker.js:146:32)
    at DisplayMarker.module.exports.DisplayMarker.setHeadScreenPosition (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/display-marker.js:154:19)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/cursor.js:67:31
    at Cursor.module.exports.Cursor.changePosition (/Applications/Atom.app/Contents/Resources/app.asar/src/cursor.js:668:7)
    at Cursor.module.exports.Cursor.setScreenPosition (/Applications/Atom.app/Contents/Resources/app.asar/src/cursor.js:65:19)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:1874:23
    at TextEditor.module.exports.TextEditor.moveCursors (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:2096:9)
    at TextEditor.module.exports.TextEditor.setCursorScreenPosition (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:1873:19)
    at TextEditorComponent.module.exports.TextEditorComponent.onMouseDown (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor-component.js:722:25)
    at HTMLDivElement.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor-component.js:3:59)
```

**Comment by QuestionPython** [comment] 2017-03-03 20:26
```
/opt/atom/resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:824
Hide Stack Trace
TypeError: Cannot read property 'locator' of null
    at GoSignatureStatusbarView.displaySignature (/home/guest/.atom/packages/go-signature-statusbar/lib/go-signature-statusbar-view.js:82:18)
    at /home/guest/.atom/packages/go-signature-statusbar/lib/go-signature-statusbar-view.js:195:14
    at Function.module.exports.Emitter.simpleDispatch (/opt/atom/resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/opt/atom/resources/app.asar/node_modules/event-kit/lib/emitter.js:129:28)
    at TextEditor.module.exports.TextEditor.cursorMoved (/opt/atom/resources/app.asar/src/text-editor.js:2087:27)
    at Selection.module.exports.Selection.markerDidChange (/opt/atom/resources/app.asar/src/selection.js:921:21)
    at /opt/atom/resources/app.asar/src/selection.js:41:24
    at Function.module.exports.Emitter.simpleDispatch (/opt/atom/resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/opt/atom/resources/app.asar/node_modules/event-kit/lib/emitter.js:129:28)
    at DisplayMarker.module.exports.DisplayMarker.notifyObservers (/opt/atom/resources/app.asar/node_modules/text-buffer/lib/display-marker.js:248:27)
    at /opt/atom/resources/app.asar/node_modules/text-buffer/lib/display-marker.js:53:26
    at Function.module.exports.Emitter.simpleDispatch (/opt/atom/resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/opt/atom/resources/app.asar/node_modules/event-kit/lib/emitter.js:129:28)
    at Marker.module.exports.Marker.emitChangeEvent (/opt/atom/resources/app.asar/node_modules/text-buffer/lib/marker.js:421:20)
    at Marker.module.exports.Marker.update (/opt/atom/resources/app.asar/node_modules/text-buffer/lib/marker.js:362:12)
    at Marker.module.exports.Marker.setHeadPosition (/opt/atom/resources/app.asar/node_modules/text-buffer/lib/marker.js:144:19)
    at DisplayMarker.module.exports.DisplayMarker.setHeadBufferPosition (/opt/atom/resources/app.asar/node_modules/text-buffer/lib/display-marker.js:146:32)
    at /opt/atom/resources/app.asar/src/cursor.js:82:31
    at Cursor.module.exports.Cursor.changePosition (/opt/atom/resources/app.asar/src/cursor.js:668:7)
    at Cursor.module.exports.Cursor.setBufferPosition (/opt/atom/resources/app.asar/src/cursor.js:80:19)
    at Selection.module.exports.Selection.insertText (/opt/atom/resources/app.asar/src/selection.js:487:23)
    at /opt/atom/resources/app.asar/node_modules/snippets/lib/snippet-expansion.js:23:43
    at TextBuffer.module.exports.TextBuffer.transact (/opt/atom/resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:819:18)
    at TextEditor.module.exports.TextEditor.transact (/opt/atom/resources/app.asar/src/text-editor.js:1551:26)
    at /opt/atom/resources/app.asar/node_modules/snippets/lib/snippet-expansion.js:22:35
    at TextBuffer.module.exports.TextBuffer.transact (/opt/atom/resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:819:18)
    at TextEditor.module.exports.TextEditor.transact (/opt/atom/resources/app.asar/src/text-editor.js:1551:26)
    at new SnippetExpansion (/opt/atom/resources/app.asar/node_modules/snippets/lib/snippet-expansion.js:19:19)
    at Object.insert (/opt/atom/resources/app.asar/node_modules/snippets/lib/snippets.js:543:14)
    at /opt/atom/resources/app.asar/node_modules/autocomplete-plus/lib/autocomplete-manager.js:660:38
    at TextBuffer.module.exports.TextBuffer.transact (/opt/atom/resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:819:18)
    at TextEditor.module.exports.TextEditor.transact (/opt/atom/resources/app.asar/src/text-editor.js:1551:26)
    at AutocompleteManager.replaceTextWithMatch (/opt/atom/resources/app.asar/node_modules/autocomplete-plus/lib/autocomplete-manager.js:646:26)
    at AutocompleteManager.confirm (/opt/atom/resources/app.asar/node_modules/autocomplete-plus/lib/autocomplete-manager.js:585:12)
    at /opt/atom/resources/app.asar/node_modules/autocomplete-plus/lib/autocomplete-manager.js:254:16
    at Function.module.exports.Emitter.simpleDispatch (/opt/atom/resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/opt/atom/resources/app.asar/node_modules/event-kit/lib/emitter.js:129:28)
    at SuggestionList.confirm (/opt/atom/resources/app.asar/node_modules/autocomplete-plus/lib/suggestion-list.js:135:27)
    at autocomplete-suggestion-list.confirmSelection (/opt/atom/resources/app.asar/node_modules/autocomplete-plus/lib/suggestion-list-element.js:326:27)
    at Function.module.exports.Emitter.simpleDispatch (/opt/atom/resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/opt/atom/resources/app.asar/node_modules/event-kit/lib/emitter.js:129:28)
    at SuggestionList.confirmSelection (/opt/atom/resources/app.asar/node_modules/autocomplete-plus/lib/suggestion-list.js:140:27)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/opt/atom/resources/app.asar/src/command-registry.js:259:29)
    at /opt/atom/resources/app.asar/src/command-registry.js:3:59
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/opt/atom/resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:599:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/opt/atom/resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:390:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (/opt/atom/resources/app.asar/src/window-event-handler.js:106:36)
    at HTMLDocument.<anonymous> (/opt/atom/resources/app.asar/src/window-event-handler.js:3:59)
```

![screenshot from 2017-03-03 23-57-02](https://cloud.githubusercontent.com/assets/25328620/23567788/3fc082f4-006d-11e7-8026-7a83407f1fc7.png)

**Comment by ironiridis** [comment] 2017-04-15 21:41
Please reopen. I encountered this behavior by clicking on an argument to `flag.StringVar`.

**Atom**: 1.16.0 ia32
**Electron**: 1.3.13
**OS**: Microsoft Windows 10 Home
**Thrown From**: [go-signature-statusbar](https://github.com/wndhydrnt/go-signature-statusbar) package 1.2.0


### Stack Trace

Uncaught TypeError: Cannot read property 'locator' of null

```
At C:\Users\User\.atom\packages\go-signature-statusbar\lib\go-signature-statusbar-view.js:82

TypeError: Cannot read property 'locator' of null
    at GoSignatureStatusbarView.displaySignature (/packages/go-signature-statusbar/lib/go-signature-statusbar-view.js:82:18)
    at /packages/go-signature-statusbar/lib/go-signature-statusbar-view.js:195:14
    at Function.module.exports.Emitter.simpleDispatch (/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/app.asar/node_modules/event-kit/lib/emitter.js:141:28)
    at TextEditor.module.exports.TextEditor.cursorMoved (/app.asar/src/text-editor.js:2131:27)
    at Selection.module.exports.Selection.markerDidChange (/app.asar/src/selection.js:921:21)
    at /app.asar/src/selection.js:41:24
    at Function.module.exports.Emitter.simpleDispatch (/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/app.asar/node_modules/event-kit/lib/emitter.js:141:28)
    at DisplayMarker.module.exports.DisplayMarker.notifyObservers (/app.asar/node_modules/text-buffer/lib/display-marker.js:248:27)
    at /app.asar/node_modules/text-buffer/lib/display-marker.js:53:26
    at Function.module.exports.Emitter.simpleDispatch (/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/app.asar/node_modules/event-kit/lib/emitter.js:141:28)
    at Marker.module.exports.Marker.emitChangeEvent (/app.asar/node_modules/text-buffer/lib/marker.js:421:20)
    at Marker.module.exports.Marker.update (/app.asar/node_modules/text-buffer/lib/marker.js:362:12)
    at Marker.module.exports.Marker.setHeadPosition (/app.asar/node_modules/text-buffer/lib/marker.js:144:19)
    at DisplayMarker.module.exports.DisplayMarker.setHeadBufferPosition (/app.asar/node_modules/text-buffer/lib/display-marker.js:146:32)
    at DisplayMarker.module.exports.DisplayMarker.setHeadScreenPosition (/app.asar/node_modules/text-buffer/lib/display-marker.js:154:19)
    at /app.asar/src/cursor.js:72:31
    at Cursor.module.exports.Cursor.changePosition (/app.asar/src/cursor.js:684:7)
    at Cursor.module.exports.Cursor.setScreenPosition (/app.asar/src/cursor.js:70:19)
    at /app.asar/src/text-editor.js:1902:23
    at TextEditor.module.exports.TextEditor.moveCursors (/app.asar/src/text-editor.js:2125:9)
    at TextEditor.module.exports.TextEditor.setCursorScreenPosition (/app.asar/src/text-editor.js:1901:19)
    at TextEditorComponent.module.exports.TextEditorComponent.onMouseDown (/app.asar/src/text-editor-component.js:721:25)
    at /app.asar/src/text-editor-component.js:3:59)
```

### Commands

```
  2x -9:28.1.0 core:confirm (input.hidden-input)
 13x -8:25.7.0 core:backspace (input.hidden-input)
     -8:23.4.0 core:confirm (input.hidden-input)
     -6:27.4.0 golang:update-tools (input.hidden-input)
  2x -1:36.7.0 application:add-project-folder (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
     -1:14.6.0 intentions:highlight (input.hidden-input)
  2x -1:14.4.0 core:save (input.hidden-input)
```

### Non-Core Packages

```
busy-signal 1.3.0 
go-debug 1.2.0 
go-plus 5.4.0 
go-signature-statusbar 1.2.0 
hyperclick 0.0.40 
intentions 1.1.2 
linter 2.1.4 
linter-ui-default 1.2.3 
```

**Comment by ironiridis** [comment] 2017-04-15 21:47
https://github.com/wndhydrnt/go-signature-statusbar/blob/8e4755fafb55d4d65ca8c14a38baa405c8cd0224/lib/go-signature-statusbar-view.js#L12

On this line, can you check for null and throw? That will help troubleshoot this issue, since clearly whatever is calling the constructor is somehow calling it without an argument.

**Comment by nkovacs** [comment] 2017-05-19 14:16
I'm getting this as well since upgrading to atom 1.17.

**Comment by harshs08** [comment] 2017-05-19 23:47
^^ Same here

**Comment by abednarik** [comment] 2017-05-23 10:38
Same issue using the latest version of **go-plus** and **atom**. Error pop-up while running a search in a particular file.

Here is the stacktrace

```
TypeError: Cannot read property 'locator' of null
    at GoSignatureStatusbarView.displaySignature (/Users/abednarik/.atom/packages/go-signature-statusbar/lib/go-signature-statusbar-view.js:82:18)
    at /Users/abednarik/.atom/packages/go-signature-statusbar/lib/go-signature-statusbar-view.js:195:14
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:25:1)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:141:1)
    at TextEditor.module.exports.TextEditor.cursorMoved (/Applications/Atom.app/Contents/Resources/app/src/text-editor.js:2136:1)
    at Selection.module.exports.Selection.markerDidChange (/Applications/Atom.app/Contents/Resources/app/src/selection.js:921:1)
    at /Applications/Atom.app/Contents/Resources/app/src/selection.js:41:1
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:25:1)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:141:1)
    at DisplayMarker.module.exports.DisplayMarker.notifyObservers (/Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/display-marker.js:248:1)
    at /Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/display-marker.js:53:1
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:25:1)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:141:1)
    at Marker.module.exports.Marker.emitChangeEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/marker.js:421:1)
    at Marker.module.exports.Marker.update (/Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/marker.js:362:1)
    at Marker.module.exports.Marker.setRange (/Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/marker.js:104:1)
    at DisplayMarker.module.exports.DisplayMarker.setBufferRange (/Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/display-marker.js:134:1)
    at /Applications/Atom.app/Contents/Resources/app/src/selection.js:107:1
    at Selection.module.exports.Selection.modifySelection (/Applications/Atom.app/Contents/Resources/app/src/selection.js:972:1)
    at Selection.module.exports.Selection.setBufferRange (/Applications/Atom.app/Contents/Resources/app/src/selection.js:100:1)
    at /Applications/Atom.app/Contents/Resources/app/src/text-editor.js:2221:1
    at TextEditor.module.exports.TextEditor.mergeSelections (/Applications/Atom.app/Contents/Resources/app/src/text-editor.js:2577:1)
    at TextEditor.module.exports.TextEditor.mergeIntersectingSelections (/Applications/Atom.app/Contents/Resources/app/src/text-editor.js:2539:1)
    at TextEditor.module.exports.TextEditor.setSelectedBufferRanges (/Applications/Atom.app/Contents/Resources/app/src/text-editor.js:2214:1)
    at TextEditor.module.exports.TextEditor.setSelectedBufferRange (/Applications/Atom.app/Contents/Resources/app/src/text-editor.js:2197:1)
    at TextEditor.module.exports.TextEditor.setSelectedScreenRange (/Applications/Atom.app/Contents/Resources/app/src/text-editor.js:2246:1)
    at FindView.selectMarkerAtIndex (/Applications/Atom.app/Contents/Resources/app/node_modules/find-and-replace/lib/find-view.js:577:1)
    at FindView.selectFirstMarkerAfterCursor (/Applications/Atom.app/Contents/Resources/app/node_modules/find-and-replace/lib/find-view.js:482:1)
    at FindView.findAndSelectResult (/Applications/Atom.app/Contents/Resources/app/node_modules/find-and-replace/lib/find-view.js:365:1)
    at FindView.findNext (/Applications/Atom.app/Contents/Resources/app/node_modules/find-and-replace/lib/find-view.js:353:1)
    at FindView.confirm (/Applications/Atom.app/Contents/Resources/app/node_modules/find-and-replace/lib/find-view.js:325:1)
    at atom-text-editor.core:confirm (/Applications/Atom.app/Contents/Resources/app/node_modules/find-and-replace/lib/find-view.js:229:1)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:265:1)
    at /Applications/Atom.app/Contents/Resources/app/src/command-registry.js:3:1
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:610:1)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:401:1)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (/Applications/Atom.app/Contents/Resources/app/src/window-event-handler.js:100:1)
    at HTMLDocument.<anonymous> (/Applications/Atom.app/Contents/Resources/app/src/window-event-handler.js:3:1)
```

**Comment by nkovacs** [comment] 2017-05-23 11:00
[The problem is that provided services are async, and their order is not guaranteed](https://github.com/atom/atom/issues/8226). If [consumeStatusBar](https://github.com/wndhydrnt/go-signature-statusbar/blob/master/lib/go-signature-statusbar.js#L43) is called before [consumeGoconfig](https://github.com/wndhydrnt/go-signature-statusbar/blob/master/lib/go-signature-statusbar.js#L39), this.goconfig will be null.
