### ISSUE TITLE
Failed to activate the go-signature-statusbar package

### ISSUE THREAD

**Issue by QuestionPython** [wndhydrnt/go-signature-statusbar#16] opened 2017-03-03 20:03 UTC
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.14.4 x64
**Electron**: 1.3.13
**OS**: Ubuntu 16.10
**Thrown From**: [go-signature-statusbar](https://github.com/wndhydrnt/go-signature-statusbar) package 1.2.0

### Stack Trace

Failed to activate the go-signature-statusbar package

```
At Cannot read property 'locator' of null

TypeError: Cannot read property 'locator' of null
    at GoSignatureStatusbarView.displaySignature (/packages/go-signature-statusbar/lib/go-signature-statusbar-view.js:82:18)
    at GoSignatureStatusbarView.activate (/packages/go-signature-statusbar/lib/go-signature-statusbar-view.js:26:12)
    at Object.addStatusBarTile (/packages/go-signature-statusbar/lib/go-signature-statusbar.js:33:37)
    at Object.consumeStatusBar (/packages/go-signature-statusbar/lib/go-signature-statusbar.js:45:10)
    at Provider.module.exports.Provider.provide (/app.asar/node_modules/service-hub/lib/provider.js:29:52)
    at ServiceHub.module.exports.ServiceHub.consume (/app.asar/node_modules/service-hub/lib/service-hub.js:50:18)
    at Package.module.exports.Package.activateServices (/app.asar/src/package.js:404:75)
    at Package.module.exports.Package.activateNow (/app.asar/src/package.js:221:16)
    at /app.asar/src/package.js:922:28
    at Function.module.exports.Emitter.simpleDispatch (/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/app.asar/node_modules/event-kit/lib/emitter.js:129:28)
    at /app.asar/src/package-manager.js:563:50
    at Set.forEach (native)
    at PackageManager.module.exports.PackageManager.activatePackage (/app.asar/src/package-manager.js:561:41)
    at /app.asar/node_modules/settings-view/lib/package-manager.js:439:29
    at exit (/app.asar/node_modules/settings-view/lib/package-manager.js:69:16)
    at triggerExitCallback (/app.asar/src/buffered-process.js:303:11)
    at /app.asar/src/buffered-process.js:324:11
    at /app.asar/src/buffered-process.js:185:9)
    at emitOne (events.js:101:20)
    at Socket.emit (events.js:188:7)
    at Pipe._handle.close [as _onclose] (net.js:493:12)
```

### Commands

```
     -8:33 core:move-right (input.hidden-input)
     -8:32.6.0 core:move-up (input.hidden-input)
     -8:32.4.0 core:move-right (input.hidden-input)
     -8:32.2.0 core:move-down (input.hidden-input)
  2x -8:31.7.0 core:move-left (input.hidden-input)
     -8:29.6.0 core:move-up (input.hidden-input)
     -8:29.5.0 core:move-right (input.hidden-input)
     -8:29.2.0 core:move-down (input.hidden-input)
     -8:29 core:move-left (input.hidden-input)
     -7:29.3.0 golang:update-tools (atom-workspace.workspace.scrollbars-visible-always.use-animations.theme-atom-material-syntax-light.theme-atom-material-ui)
     -2:39.6.0 core:move-right (input.hidden-input)
     -2:39.3.0 core:select-all (input.hidden-input)
     -2:39.1.0 core:move-right (input.hidden-input)
  2x -2:38.8.0 core:save (input.hidden-input)
 29x -2:25.8.0 window:decrease-font-size (span.)
     -2:22.4.0 window:increase-font-size (span.)
```

### Non-Core Packages

```
atom-material-syntax-light 0.4.6 
atom-material-ui 1.3.9 
go-debug 1.1.0 
go-plus 5.2.0 
go-rename 0.3.0 
go-signature-statusbar 1.2.0 
hyperclick 0.0.40 
linter 1.11.23 
linter-golinter 1.2.1 
```

**Comment by ironiridis** [comment] 2017-04-15 21:52
Duplicate of #13, which should probably be re-opened...

**Comment by davidsbond** [comment] 2017-04-15 23:31
Had the same issue when opening atom. This has broken for me after upgrading go-plus to 5.4.0

`[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.15.0 ia32
**Electron**: 1.3.13
**OS**: Ubuntu 16.10
**Thrown From**: [go-signature-statusbar](https://github.com/wndhydrnt/go-signature-statusbar) package 1.2.0


### Stack Trace

Uncaught TypeError: Cannot read property 'locator' of null

```
At /home/david/.atom/packages/go-signature-statusbar/lib/go-signature-statusbar-view.js:82

TypeError: Cannot read property 'locator' of null
    at GoSignatureStatusbarView.displaySignature (/packages/go-signature-statusbar/lib/go-signature-statusbar-view.js:82:18)
    at GoSignatureStatusbarView.activate (/packages/go-signature-statusbar/lib/go-signature-statusbar-view.js:26:12)
    at /packages/go-signature-statusbar/lib/go-signature-statusbar.js:30:39
    at Function.module.exports.Emitter.simpleDispatch (/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/app.asar/node_modules/event-kit/lib/emitter.js:129:28)
    at /app.asar/src/pane-container.js:348:27
    at Function.module.exports.Emitter.simpleDispatch (/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/app.asar/node_modules/event-kit/lib/emitter.js:129:28)
    at Pane.module.exports.Pane.setActiveItem (/app.asar/src/pane.js:300:22)
    at Pane.module.exports.Pane.activateItemAtIndex (/app.asar/src/pane.js:435:19)
    at Pane.module.exports.Pane.activatePreviousItem (/app.asar/src/pane.js:400:21)
    at Pane.module.exports.Pane.removeItem (/app.asar/src/pane.js:585:16)
    at Pane.module.exports.Pane.destroyItem (/app.asar/src/pane.js:658:16)
    at TabBarView.module.exports.TabBarView.closeTab (/app.asar/node_modules/tabs/lib/tab-bar-view.js:333:26)
    at HTMLDivElement.TabView.didClickCloseIcon (/app.asar/node_modules/tabs/lib/tab-bar-view.js:222:19)
```

### Commands

```
     -7:36.4.0 command-palette:toggle (div.panels-item)
 15x -7:31.3.0 core:backspace (input.hidden-input)
     -7:22 editor:consolidate-selections (input.hidden-input)
     -7:22 core:cancel (input.hidden-input)
     -7:21.7.0 core:backspace (div.panels-item)
     -6:23.1.0 settings-view:uninstall-packages (input.hidden-input)
     -5:54 intentions:highlight (input.hidden-input)
     -5:53.9.0 core:save (input.hidden-input)
     -5:49.1.0 grammar-selector:show (atom-text-editor.editor.is-focused)
  4x -5:44.2.0 core:backspace (input.hidden-input)
     -5:42.4.0 core:confirm (input.hidden-input)
     -5:39.3.0 linter-ui-default:toggle-panel (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
```

### Non-Core Packages

```
busy-signal 1.3.0 
go-debug 1.2.0 
go-plus undefined 
go-signature-statusbar 1.2.0 
hyperclick 0.0.40 
intentions 1.1.2 
linter 2.1.4 
linter-ui-default 1.2.3 
```

`

**Closed as completed** 2017-07-13 17:23 UTC

**Comment by universonic** [comment] 2017-08-17 08:50
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.19.2 x64
**Electron**: 1.6.9
**OS**: Mac OS X 10.12.6
**Thrown From**: [go-signature-statusbar](https://github.com/wndhydrnt/go-signature-statusbar) package 1.2.1


### Stack Trace

Failed to activate the go-signature-statusbar package

```
At Cannot read property 'match' of undefined

TypeError: Cannot read property 'match' of undefined
    at GoSignatureStatusbarView.extractFunc (/packages/go-signature-statusbar/lib/go-signature-statusbar-view.js:117:23)
    at GoSignatureStatusbarView.displaySignature (/packages/go-signature-statusbar/lib/go-signature-statusbar-view.js:49:21)
    at GoSignatureStatusbarView.activate (/packages/go-signature-statusbar/lib/go-signature-statusbar-view.js:25:12)
    at Object.addStatusBarTile (/packages/go-signature-statusbar/lib/go-signature-statusbar.js:33:37)
    at Object.consumeStatusBar (/packages/go-signature-statusbar/lib/go-signature-statusbar.js:46:10)
    at Provider.module.exports.Provider.provide (/Applications/Atom.app/Contents/Resources/app/node_modules/service-hub/lib/provider.js:34:58)
    at ServiceHub.module.exports.ServiceHub.consume (/Applications/Atom.app/Contents/Resources/app/node_modules/service-hub/lib/service-hub.js:50:24)
    at Package.module.exports.Package.activateServices (/Applications/Atom.app/Contents/Resources/app/src/package.js:454:81)
    at Package.module.exports.Package.activateNow (/Applications/Atom.app/Contents/Resources/app/src/package.js:256:22)
    at /Applications/Atom.app/Contents/Resources/app/src/package.js:1014:34
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:141:34)
    at /Applications/Atom.app/Contents/Resources/app/src/package-manager.js:658:56
    at Set.forEach (native)
    at PackageManager.module.exports.PackageManager.activatePackage (/Applications/Atom.app/Contents/Resources/app/src/package-manager.js:656:47)
    at /Applications/Atom.app/Contents/Resources/app/node_modules/settings-view/lib/package-manager.js:535:35
    at exit (/Applications/Atom.app/Contents/Resources/app/node_modules/settings-view/lib/package-manager.js:128:22)
    at triggerExitCallback (/Applications/Atom.app/Contents/Resources/app/src/buffered-process.js:338:17)
    at /Applications/Atom.app/Contents/Resources/app/src/buffered-process.js:359:17
    at Socket.<anonymous> (/Applications/Atom.app/Contents/Resources/app/src/buffered-process.js:220:15)
    at emitOne (events.js:101:20)
    at Socket.emit (events.js:188:7)
    at Pipe._handle.close [as _onclose] (net.js:501:12)
```

### Commands

```
     -2:16.1.0 tree-view:show (atom-workspace.workspace.scrollbars-visible-always)
```

### Non-Core Packages

```
angularjs 0.4.0 
atom-beautify 0.30.5 
atom-clock 0.1.13 
atom-ctags 5.1.0 
atom-format-lua 0.1.5 
atom-runner 2.7.1 
atom-typescript 11.0.7 
build 0.68.0 
busy 0.7.0 
busy-signal 1.4.3 
docker 0.7.0 
emmet 2.4.3 
file-icons 2.1.11 
git-plus 7.9.3 
git-status 0.3.4 
go-debug 1.5.0 
go-imports 0.1.1 
go-plus 5.5.5 
go-signature-statusbar 1.2.1 
highlight-line 0.12.0 
highlight-selected 0.13.1 
hyperclick 0.1.3 
intentions 1.1.5 
language-docker 1.1.8 
language-lua 0.9.11 
language-plantuml 0.2.0 
linter 2.2.0 
linter-docker 0.2.0 
linter-golinter 1.2.2 
linter-lua 1.0.4 
linter-luacheck 2.0.1 
linter-ui-default 1.6.7 
markdown-writer 2.6.5 
open-in-browser 0.5.2 
plantuml-viewer 0.7.2 
platformio-ide-terminal 2.5.5 
relative-numbers 0.8.0 
Sublime-Style-Column-Selection 1.7.4 
vim-mode-plus 0.97.2 
vim-mode-plus-duplicate 0.2.0 
vim-mode-plus-ex-mode 0.9.1 
vim-mode-plus-exchange 0.2.1 
vim-mode-plus-jasmine-increase-focus 0.3.0 
vim-mode-plus-keymaps-for-surround 0.2.1 
vim-mode-plus-move-selected-text 0.10.0 
vim-mode-plus-move-to-symbols 0.3.0 
vim-mode-plus-project-find-from-search 0.2.0 
vim-mode-plus-replace-with-execution 0.1.3 
vim-mode-plus-subword-movement 0.2.2 
Zen 0.18.0 
```

**Comment by universonic** [comment] 2017-08-17 08:55
@wndhydrnt Could u help me to resolve this?
